version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'discord_voice_channel_manage'
    working_dir: '/app/'
    tty: true
    command: python entry.py
    # volumes:
    #   - ./app/:/app/
